name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"   # Runs every 12 hours
  workflow_dispatch:          # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0     # Fetch all history for all branches

      - name: Generate snake animation SVG
        uses: Platane/snk@v3
        with:
          github_user_name: mahithiredd
          outputs: |
            output/github-contribution-grid-snake.svg

      - name: Configure Git for pushing
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Checkout output branch or create if missing
        run: |
          git fetch origin output || echo "No output branch yet"
          if git rev-parse --verify origin/output; then
            git checkout output
            git reset --hard origin/output
          else
            git checkout -b output
          fi

      - name: Copy generated SVG to repo root (if needed)
        run: |
          mkdir -p output
          # This assumes the SVG is created somewhere else, but Platane/snk writes directly
          # If generated in different path, adjust accordingly

      - name: Commit and push changes
        run: |
          git add output/github-contribution-grid-snake.svg
          git commit -m "Update snake animation" || echo "No changes to commit"
          git push origin output --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
